version: '3.8'

services:
  spark-master:
    build: .
    # image: interview-spark:3.5-debian12
    hostname: spark-master
    ports:
      - "8080:8080" # Spark Ui
      - "7077:7077" # Master URL
      - "4040:4040" # Spark app
      - "8888:8888" # Jupyter notebbok
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
    environment:
      - SPARK_MODE=master # Must be exactly 'master' or 'worker'
    mem_limit: 2G
    cpus: 1.0

  spark-worker:
    image: interview-spark:3.5-debian12 # Use built image
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
    mem_limit: 2G
    cpus: 1.0
    scale: 2

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: interview
      POSTGRES_PASSWORD: practice
      POSTGRES_DB: interview_prep_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:


networks:
  default:
    name: spark-network
